################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
uCOS-III/Source/os_cfg_app.obj: /home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source/os_cfg_app.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me -O2 -g --include_path="/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/CFG" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/uCOS-III-Ex1" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/OS" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/RIT" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/CPU/LuminaryMicro/DriverLib/driverlib" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-LIB" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU/ARM-Cortex-M3/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Ports/ARM-Cortex-M3/Generic/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Ports/LuminaryMicro/LM3Sxxxx" --gcc --define=ccs="ccs" --define=PART_LM3S9B96 --define=TARGET_IS_TEMPEST_RB1 --define=UART_BUFFERED --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="uCOS-III/Source/os_cfg_app.pp" --obj_directory="uCOS-III/Source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

uCOS-III/Source/os_core.obj: /home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source/os_core.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me -O2 -g --include_path="/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/CFG" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/uCOS-III-Ex1" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/OS" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/RIT" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/CPU/LuminaryMicro/DriverLib/driverlib" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-LIB" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU/ARM-Cortex-M3/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Ports/ARM-Cortex-M3/Generic/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Ports/LuminaryMicro/LM3Sxxxx" --gcc --define=ccs="ccs" --define=PART_LM3S9B96 --define=TARGET_IS_TEMPEST_RB1 --define=UART_BUFFERED --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="uCOS-III/Source/os_core.pp" --obj_directory="uCOS-III/Source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

uCOS-III/Source/os_dbg.obj: /home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source/os_dbg.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me -O2 -g --include_path="/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/CFG" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/uCOS-III-Ex1" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/OS" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/RIT" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/CPU/LuminaryMicro/DriverLib/driverlib" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-LIB" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU/ARM-Cortex-M3/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Ports/ARM-Cortex-M3/Generic/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Ports/LuminaryMicro/LM3Sxxxx" --gcc --define=ccs="ccs" --define=PART_LM3S9B96 --define=TARGET_IS_TEMPEST_RB1 --define=UART_BUFFERED --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="uCOS-III/Source/os_dbg.pp" --obj_directory="uCOS-III/Source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

uCOS-III/Source/os_flag.obj: /home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source/os_flag.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me -O2 -g --include_path="/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/CFG" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/uCOS-III-Ex1" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/OS" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/RIT" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/CPU/LuminaryMicro/DriverLib/driverlib" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-LIB" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU/ARM-Cortex-M3/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Ports/ARM-Cortex-M3/Generic/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Ports/LuminaryMicro/LM3Sxxxx" --gcc --define=ccs="ccs" --define=PART_LM3S9B96 --define=TARGET_IS_TEMPEST_RB1 --define=UART_BUFFERED --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="uCOS-III/Source/os_flag.pp" --obj_directory="uCOS-III/Source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

uCOS-III/Source/os_int.obj: /home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source/os_int.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me -O2 -g --include_path="/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/CFG" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/uCOS-III-Ex1" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/OS" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/RIT" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/CPU/LuminaryMicro/DriverLib/driverlib" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-LIB" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU/ARM-Cortex-M3/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Ports/ARM-Cortex-M3/Generic/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Ports/LuminaryMicro/LM3Sxxxx" --gcc --define=ccs="ccs" --define=PART_LM3S9B96 --define=TARGET_IS_TEMPEST_RB1 --define=UART_BUFFERED --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="uCOS-III/Source/os_int.pp" --obj_directory="uCOS-III/Source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

uCOS-III/Source/os_mem.obj: /home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source/os_mem.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me -O2 -g --include_path="/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/CFG" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/uCOS-III-Ex1" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/OS" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/RIT" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/CPU/LuminaryMicro/DriverLib/driverlib" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-LIB" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU/ARM-Cortex-M3/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Ports/ARM-Cortex-M3/Generic/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Ports/LuminaryMicro/LM3Sxxxx" --gcc --define=ccs="ccs" --define=PART_LM3S9B96 --define=TARGET_IS_TEMPEST_RB1 --define=UART_BUFFERED --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="uCOS-III/Source/os_mem.pp" --obj_directory="uCOS-III/Source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

uCOS-III/Source/os_msg.obj: /home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source/os_msg.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me -O2 -g --include_path="/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/CFG" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/uCOS-III-Ex1" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/OS" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/RIT" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/CPU/LuminaryMicro/DriverLib/driverlib" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-LIB" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU/ARM-Cortex-M3/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Ports/ARM-Cortex-M3/Generic/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Ports/LuminaryMicro/LM3Sxxxx" --gcc --define=ccs="ccs" --define=PART_LM3S9B96 --define=TARGET_IS_TEMPEST_RB1 --define=UART_BUFFERED --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="uCOS-III/Source/os_msg.pp" --obj_directory="uCOS-III/Source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

uCOS-III/Source/os_mutex.obj: /home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source/os_mutex.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me -O2 -g --include_path="/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/CFG" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/uCOS-III-Ex1" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/OS" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/RIT" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/CPU/LuminaryMicro/DriverLib/driverlib" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-LIB" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU/ARM-Cortex-M3/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Ports/ARM-Cortex-M3/Generic/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Ports/LuminaryMicro/LM3Sxxxx" --gcc --define=ccs="ccs" --define=PART_LM3S9B96 --define=TARGET_IS_TEMPEST_RB1 --define=UART_BUFFERED --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="uCOS-III/Source/os_mutex.pp" --obj_directory="uCOS-III/Source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

uCOS-III/Source/os_pend_multi.obj: /home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source/os_pend_multi.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me -O2 -g --include_path="/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/CFG" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/uCOS-III-Ex1" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/OS" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/RIT" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/CPU/LuminaryMicro/DriverLib/driverlib" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-LIB" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU/ARM-Cortex-M3/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Ports/ARM-Cortex-M3/Generic/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Ports/LuminaryMicro/LM3Sxxxx" --gcc --define=ccs="ccs" --define=PART_LM3S9B96 --define=TARGET_IS_TEMPEST_RB1 --define=UART_BUFFERED --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="uCOS-III/Source/os_pend_multi.pp" --obj_directory="uCOS-III/Source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

uCOS-III/Source/os_prio.obj: /home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source/os_prio.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me -O2 -g --include_path="/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/CFG" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/uCOS-III-Ex1" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/OS" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/RIT" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/CPU/LuminaryMicro/DriverLib/driverlib" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-LIB" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU/ARM-Cortex-M3/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Ports/ARM-Cortex-M3/Generic/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Ports/LuminaryMicro/LM3Sxxxx" --gcc --define=ccs="ccs" --define=PART_LM3S9B96 --define=TARGET_IS_TEMPEST_RB1 --define=UART_BUFFERED --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="uCOS-III/Source/os_prio.pp" --obj_directory="uCOS-III/Source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

uCOS-III/Source/os_q.obj: /home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source/os_q.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me -O2 -g --include_path="/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/CFG" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/uCOS-III-Ex1" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/OS" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/RIT" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/CPU/LuminaryMicro/DriverLib/driverlib" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-LIB" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU/ARM-Cortex-M3/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Ports/ARM-Cortex-M3/Generic/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Ports/LuminaryMicro/LM3Sxxxx" --gcc --define=ccs="ccs" --define=PART_LM3S9B96 --define=TARGET_IS_TEMPEST_RB1 --define=UART_BUFFERED --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="uCOS-III/Source/os_q.pp" --obj_directory="uCOS-III/Source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

uCOS-III/Source/os_sem.obj: /home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source/os_sem.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me -O2 -g --include_path="/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/CFG" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/uCOS-III-Ex1" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/OS" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/RIT" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/CPU/LuminaryMicro/DriverLib/driverlib" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-LIB" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU/ARM-Cortex-M3/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Ports/ARM-Cortex-M3/Generic/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Ports/LuminaryMicro/LM3Sxxxx" --gcc --define=ccs="ccs" --define=PART_LM3S9B96 --define=TARGET_IS_TEMPEST_RB1 --define=UART_BUFFERED --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="uCOS-III/Source/os_sem.pp" --obj_directory="uCOS-III/Source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

uCOS-III/Source/os_stat.obj: /home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source/os_stat.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me -O2 -g --include_path="/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/CFG" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/uCOS-III-Ex1" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/OS" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/RIT" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/CPU/LuminaryMicro/DriverLib/driverlib" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-LIB" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU/ARM-Cortex-M3/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Ports/ARM-Cortex-M3/Generic/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Ports/LuminaryMicro/LM3Sxxxx" --gcc --define=ccs="ccs" --define=PART_LM3S9B96 --define=TARGET_IS_TEMPEST_RB1 --define=UART_BUFFERED --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="uCOS-III/Source/os_stat.pp" --obj_directory="uCOS-III/Source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

uCOS-III/Source/os_task.obj: /home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source/os_task.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me -O2 -g --include_path="/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/CFG" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/uCOS-III-Ex1" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/OS" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/RIT" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/CPU/LuminaryMicro/DriverLib/driverlib" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-LIB" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU/ARM-Cortex-M3/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Ports/ARM-Cortex-M3/Generic/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Ports/LuminaryMicro/LM3Sxxxx" --gcc --define=ccs="ccs" --define=PART_LM3S9B96 --define=TARGET_IS_TEMPEST_RB1 --define=UART_BUFFERED --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="uCOS-III/Source/os_task.pp" --obj_directory="uCOS-III/Source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

uCOS-III/Source/os_tick.obj: /home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source/os_tick.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me -O2 -g --include_path="/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/CFG" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/uCOS-III-Ex1" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/OS" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/RIT" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/CPU/LuminaryMicro/DriverLib/driverlib" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-LIB" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU/ARM-Cortex-M3/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Ports/ARM-Cortex-M3/Generic/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Ports/LuminaryMicro/LM3Sxxxx" --gcc --define=ccs="ccs" --define=PART_LM3S9B96 --define=TARGET_IS_TEMPEST_RB1 --define=UART_BUFFERED --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="uCOS-III/Source/os_tick.pp" --obj_directory="uCOS-III/Source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

uCOS-III/Source/os_time.obj: /home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source/os_time.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me -O2 -g --include_path="/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/CFG" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/uCOS-III-Ex1" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/OS" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/RIT" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/CPU/LuminaryMicro/DriverLib/driverlib" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-LIB" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU/ARM-Cortex-M3/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Ports/ARM-Cortex-M3/Generic/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Ports/LuminaryMicro/LM3Sxxxx" --gcc --define=ccs="ccs" --define=PART_LM3S9B96 --define=TARGET_IS_TEMPEST_RB1 --define=UART_BUFFERED --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="uCOS-III/Source/os_time.pp" --obj_directory="uCOS-III/Source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

uCOS-III/Source/os_tmr.obj: /home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source/os_tmr.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me -O2 -g --include_path="/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/CFG" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/uCOS-III-Ex1" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/OS" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/RIT" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/CPU/LuminaryMicro/DriverLib/driverlib" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-LIB" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU/ARM-Cortex-M3/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Ports/ARM-Cortex-M3/Generic/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Ports/LuminaryMicro/LM3Sxxxx" --gcc --define=ccs="ccs" --define=PART_LM3S9B96 --define=TARGET_IS_TEMPEST_RB1 --define=UART_BUFFERED --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="uCOS-III/Source/os_tmr.pp" --obj_directory="uCOS-III/Source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

uCOS-III/Source/os_var.obj: /home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source/os_var.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/bin/armcl" -mv7M3 --code_state=16 --abi=eabi -me -O2 -g --include_path="/opt/ti/ccsv6/tools/compiler/ti-cgt-arm_5.2.6/include" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/CFG" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/uCOS-III-Ex1" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/OS" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/EvalBoards/TI/EKS-LM3S8962/CCS6/SOURCE/BSP/RIT" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/CPU/LuminaryMicro/DriverLib/driverlib" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-LIB" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-CPU/ARM-Cortex-M3/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uCOS-III/Ports/ARM-Cortex-M3/Generic/CCS5" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Source" --include_path="/home/max_power/GitHub/Projektarbeit/Micrium/Software/uC-Probe/Target/Communication/Generic/RS-232/Ports/LuminaryMicro/LM3Sxxxx" --gcc --define=ccs="ccs" --define=PART_LM3S9B96 --define=TARGET_IS_TEMPEST_RB1 --define=UART_BUFFERED --diag_warning=225 --display_error_number --gen_func_subsections=on --preproc_with_compile --preproc_dependency="uCOS-III/Source/os_var.pp" --obj_directory="uCOS-III/Source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '


